edumax/config/routes.rb
Rails.application.routes.draw do
  get 'admin/basic'

  get 'admin/advanced'

  resources :courses

  resources :news

  mount Ckeditor::Engine => '/ckeditor'
  resources :articles do
    collection do
      get :tag
    end
  end

  root to: 'home#index'
  
  match ':controller(/:action(/:id))', :via => [:get, :post]

  devise_for :users, controllers: { sessions: "users/sessions", 
                                    confirmations: "users/confirmations",
                                    registrations: "users/registrations", 
                                    passwords: "users/passwords",
                                    unlocks: "users/unlocks"}

end

edumax/app/views/layouts/_article_form.html.erb
<%= form_for @article do |f| %>
  <div class="form-group">
    <%= f.label :title, class: 'control-label' %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :body, class: 'control-label' %>
    <%= f.cktext_area :body, rows: 10, :ckeditor => {:uiColor => '#AADC6E', :toolbar => 'Full'} %>
  </div>
  <div class="form-group">
    <%= f.label :tag_list, "Tags (separated by commas)", class: 'control-label' %><br />
  <%= f.text_field :tag_list, class: 'form-control'%>
</div>
  <div class="actions">
    <%= f.submit 'Save', class: 'btn btn-success' %>
  </div>
<% end %>

edumax/app/views/layouts/_error.html.erb
<% flash.each do |key, value| %>
    <% if value.class == Array %>
        <div class="<%= flash_class(key) %>">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <% value.each do |message| %>  
                <%= message %>
                </br>
            <% end %>
        </div>
    <% else %>
        <div class="<%= flash_class(key) %>">
    	    <button type="button" class="close" data-dismiss="alert">×</button>
            <%= value %>
        </div>
    <% end %>
<% end %>

edumax/app/views/layouts/_header_nav.html.erb
<header class="navbar navbar-fixed-top navbar-default">

<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav ">
        <li><strong><%= link_to "Edumax", {:controller => '/home', :action => 'index'}, class: 'navbar-brand logo_link' %></strong></li>
        <li class="divider-vertical"></li>
        <li><%= link_to "News", {:controller => '/news', :action => 'index'}%></li>
        <li><%= link_to "Blog", {:controller => '/articles', :action => 'index'}%></li>
        <li><%= link_to "Admin", {:controller => '/admin', :action => 'advanced'}%></li>
        <li><%= link_to "Courses", courses_path%></li>
        <li class="divider-vertical"></li>
        <% if user_signed_in? %>
        <%if current_user.admin? %>
        <li><%= link_to "Admin", '#'%></li>
        <% else
         end%>
         <%end%>
      </ul>
        <ul class="nav navbar-nav navbar-right">

        <% if user_signed_in? %>
        
        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
          <%= image_tag current_user.image(:small), {class: 'circular-small'} %> <%= current_user.first_name %>

       <b class="caret"></b></a>
        <ul class="dropdown-menu">
          
          <li><%= link_to('Profile', edit_user_registration_path) %></li>
          <li><a href="#">Something else here</a></li>
          <li class="divider"></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete%></li>
        </ul>
      </li>

      <% else
         end%>
      </ul>
    </div>
</header>

edumax/app/views/layouts/_links.html.erb
<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

edumax/app/views/layouts/_sidepanel.html.erb
<div class="sidepanel text-center" , id='sticker'>
    <br>
    <%= image_tag current_user.image.url(:med), {class: " circular-med"} %>
    <div class='panels_item'>
        <b><%= current_user.first_name %>
        <%= current_user.last_name %></b>
    </div>
    <div class='panels_item', style='color:#bbb;'><%= get_rank(current_user) %></div>
    <%= link_to "New Article", new_article_path, class: 'brand' %>
    <div class='text-left panels_item panel_heading'>Most recent posts:</div>
    <div class='text-left panels_item panel_body'>
        <% @recent.each do |r| %>
            <small><%= r.title %></small>
            <% if r != @recent.last %>
                <br />
            <% end %>
        <%end%>
    </div>
    <div class='text-left panels_item panel_heading'>Tags:</div>
    <div id="tag_cloud", class="text-center panels_item panel_body">
        <% tag_cloud Article.tag_counts, %w{s m l} do |tag, css_class| %>
            <%= link_to tag.name, { :action => :tag, :tag => tag.name }, class: (css_class + ' '+'label label-info')%>
        <% end %>
    </div>
</div>

edumax/app/views/layouts/_user_email_changed_alert.html.erb
  <!-- Alert in case user changed email and didn't confirm -->
    <div class="alert alert-dismissible alert-info">Currently waiting confirmation for: <%= resource.unconfirmed_email %>
    <button type="button" class="close" data-dismiss="alert">×</button></div>

edumax/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Edumax</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header_nav' %>
<%= yield %>
<script>hljs.initHighlightingOnLoad();</script>
</body>
</html>