edumax/config/routes.rb
Rails.application.routes.draw do
  get 'admin/basic'

  get 'admin/advanced'

  resources :courses

  resources :news

  mount Ckeditor::Engine => '/ckeditor'
  resources :articles do
    collection do
      get :tag
    end
  end

  root to: 'home#index'
  
  match ':controller(/:action(/:id))', :via => [:get, :post]

  devise_for :users, controllers: { sessions: "users/sessions", 
                                    confirmations: "users/confirmations",
                                    registrations: "users/registrations", 
                                    passwords: "users/passwords",
                                    unlocks: "users/unlocks"}

end

edumax/app/views/layouts/EditUserFormHelpers/_edit_info_modal.html.erb
  <!-- Edit Info Modal -->
  <div class="modal" id="edit_info">
    <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: {method: :put }) do |f| %> 
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h4 class="modal-title">Edit basic info</h4>
          </div>
          <div class="modal-body">
            <div class="form-group">
              <%= f.label :birthday, class: 'control-label' %><br />
              <%= f.date_select :birthday, {:start_year=>1900}, {class: 'form-control-date'}  %>
            </div>  
            <div class="form-group">
              <%= f.label :email, "Change Email", class: 'control-label' %><br />
              <%= f.email_field :email, autofocus: true, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :telephone, class: 'control-label' %><br />
              <%= f.telephone_field :telephone, class: 'form-control'%>
            </div>
            <div class="form-group">
              <%= f.label :address, class: 'control-label' %><br />
              <%= f.text_field :address, class: 'form-control' %>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= f.submit "Save", class: 'btn btn-success'  %>
          </div>
        </div>
      </div>
    <%end%>
  </div>   

edumax/app/views/layouts/EditUserFormHelpers/_edit_name_modal.html.erb
<!-- Edit Name Modal -->
  <div class="modal" id="edit_name">
    <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: {method: :put }) do |f| %> 
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h4 class="modal-title">Edit Name</h4>
          </div>
          <div class="modal-body">
            <div class="form-group">
              <%= f.label :first_name, "First name", class: 'control-label' %> 
              <%= f.text_field :first_name, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :last_name, "Last name", class: 'control-label' %><br />
              <%= f.text_field :last_name, class: 'form-control' %>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= f.submit "Save", class: 'btn btn-success'  %>
          </div>
        </div>
      </div>
    <%end%>
  </div>    

edumax/app/views/layouts/EditUserFormHelpers/_edit_password_modal.html.erb
<!-- Edit Password Modal -->
  <div class="modal" id="edit_password">
    <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: {method: :put }) do |f| %> 
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h4 class="modal-title">Edit Password</h4>
          </div>
          <div class="modal-body">
            <div class="form-group">
              <%= f.label :password, "Change Password", class: 'control-label' %> 
              <i>(leave blank if you don't want to change it)</i><br />
              <%= f.password_field :password, autocomplete: "off", class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :password_confirmation, "New Password Confirmation", class: 'control-label' %><br />
              <%= f.password_field :password_confirmation, autocomplete: "off", class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :current_password, "Current Password", class: 'control-label' %><br />
              <%= f.password_field :current_password, autocomplete: "off", class: 'form-control' %>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= f.submit "Save", class: 'btn btn-success'  %>
          </div>
        </div>
      </div>
    <%end%>
  </div>    

edumax/app/views/layouts/EditUserFormHelpers/_select_image_modal.html.erb
  <!-- Create the imagepicker array -->
  <% img_paths = Array.new %>
  <% @images.each do |image| %>
  <%img_paths.push([
    '',
    "/assets/images/users/#{current_user.id}/original/#{image.split('/').last}",
    {'data-img-src'=>"/assets/images/users/#{current_user.id}/med/#{image.split('/').last}"}
    ])%>
  <% end %>
  <!-- Select from gallery modal -->
  <div class="modal" id="image_select">
    <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: {method: :put }) do |f| %> 
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h4 class="modal-title">My profile pictures</h4>
          </div>
          <div class="modal-body med_pic_select">
              <%=f.select(:image_file_path, options_for_select(img_paths), {}, {class: 'image-picker'})%> 
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= f.submit "Select", class: 'btn btn-success'  %>
          </div>
        </div>
      </div>
    <%end%>
  </div>

<script type="text/javascript">$('select.image-picker').imagepicker()</script>

edumax/app/views/layouts/EditUserFormHelpers/_upload_image_button.html.erb
  <!-- Upload Button -->
  <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: {:multipart => true }) do |f| %>
    <div class="form-group">
      <label for = 'file-upload', class='btn btn-large btn-block btn-info'>
        <span class="glyphicon glyphicon-upload" aria-hidden="true"></span> Upload Picture
        <%= f.file_field :image, id: "file-upload", onchange: "this.form.submit()" %>
      </label>
    </div>
  <% end %>