edumax/config/routes.rb
Rails.application.routes.draw do
  get 'admin/basic'

  get 'admin/advanced'

  resources :courses

  resources :news

  mount Ckeditor::Engine => '/ckeditor'
  resources :articles do
    collection do
      get :tag
    end
  end

  root to: 'home#index'
  
  match ':controller(/:action(/:id))', :via => [:get, :post]

  devise_for :users, controllers: { sessions: "users/sessions", 
                                    confirmations: "users/confirmations",
                                    registrations: "users/registrations", 
                                    passwords: "users/passwords",
                                    unlocks: "users/unlocks"}

end

edumax/app/models/news.rb
class News < ActiveRecord::Base
end

edumax/app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @users = User.all
    @recent = News.all.order("created_at desc").limit(5)
    @news = News.all.page(params[:page]).per(5).order("created_at DESC")

    respond_with(@news)
  end

  def show
    respond_with(@news)
  end

  def new
    @news = News.new
    respond_with(@news)
  end

  def edit
  end

  def create
    @recent = News.all.order("created_at desc").limit(5)
    @news = News.new(news_params)
    @news.author = current_user.id
    if @news.save
      redirect_to news_index_path, notice: "The news has been successfully created."
    else
      flash[:error] = @news.errors.full_messages
      render :new
    end
  end

  def update
    @news.update(news_params)
    respond_with(@news)
  end

  def delete
    @done = News.find(params[:id])
    if @done.destroy
      redirect_to news_index_path, notice: "The news has been successfully deleted."
    else
      redirect_to news_index_path, notice: "The news could not be deleted."
    end
  end

  private
    def set_news
      @news = News.find(params[:id])
    end

    def news_params
      params.require(:news).permit(:author, :content, :sticky)
    end
end

edumax/app/helpers/news_helper.rb
module NewsHelper
end

edumax/app/views/news/_form.html.erb
<%= form_for(@news) do |f| %>

  <div class="form-group">
    <%= f.label :content, class: 'control-label' %><br>
    <%= f.text_field :content, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.check_box :sticky %>
    <%= f.label :sticky, class: 'control-label' %>
    
  </div>
  <div class="actions">
    <%= f.submit "Save", class: 'btn btn-success'%>
  </div>
<% end %>

edumax/app/views/news/edit.html.erb
<h1>Editing news</h1>

<%= render 'form' %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

edumax/app/views/news/index.html.erb
    <div class="col-md-9 col-md-offset-3">
        <div class='row'>
            <div class="col-md-10 col-md-offset-1">
                
                <h1 style='color:#22aaaa;'><span class="glyphicon glyphicon-th-large" aria-hidden="true"></span> Edumax News</h1>
                
                <%= render 'layouts/error' %>
            </br>
                <% @news.each do |neww| %>
                    <div class='article_post'>
                        <div class='modal-body wordwrap'>
                            <%= image_tag @users.find(neww.author).image.url(:smallish), {class: " circular-smallish"} %>
                            <%= neww.content %>
                           <br>

                             <small class="text-muted">Posted on: <%=neww.created_at.strftime("%B #{current_user.created_at.day.ordinalize}, %Y")%>| by <%= @users.find(neww.author).first_name%>
                                <%= @users.find(neww.author).last_name%>
                            </small>
                           
                            
                            <%= link_to "Edit", edit_news_path(neww) %> |
                             <%= link_to "Delete", {:controller => '/news', :action => "delete", :id => neww.id} %>|
                              <%= link_to 'View', {:controller => '/news', :action =>'show', :id => neww.id} %>

                        </div>
                    </div>
                    <% if neww != @news.last %>
                    <br />
                    <% end %>
                    
                <% end %>
                <div class="text-center"><%= paginate @news, :theme => 'twitter-bootstrap-3' %></div>
            </div>
        </div>
    </div>  

<div class="sidepanel text-center" , id='sticker'>
    <br>
    <%= image_tag current_user.image.url(:med), {class: " circular-med"} %>
    <div class='panels_item'>
        <b><%= current_user.first_name %>
        <%= current_user.last_name %></b>
    </div>
    <div class='panels_item', style='color:#bbb;'><%= get_rank(current_user) %></div>
    <%= link_to "Add Post", {:controller => '/news', :action =>'new'}, class: 'brand' %>
</div>

edumax/app/views/news/new.html.erb
    <div class="col-md-9 col-md-offset-3">
        <div class='row'>

            <div class="col-md-10 col-md-offset-1">
        <%= render "layouts/error" %>
        <div class='article_post'>
<h1>New news</h1>

<%= render 'form' %>

        </div>
    </div>
                </div>
        </div>
    </div>  

edumax/app/views/news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @news.author %>
</p>

<p>
  <strong>Content:</strong>
  <%= @news.content %>
</p>

<p>
  <strong>Sticky:</strong>
  <%= @news.sticky %>
</p>

<%= link_to 'Edit', edit_news_path(@news) %> |
<%= link_to 'Back', news_index_path %>