edumax/config/routes.rb
Rails.application.routes.draw do
  get 'admin/basic'

  get 'admin/advanced'

  resources :courses

  resources :news

  mount Ckeditor::Engine => '/ckeditor'
  resources :articles do
    collection do
      get :tag
    end
  end

  root to: 'home#index'
  
  match ':controller(/:action(/:id))', :via => [:get, :post]

  devise_for :users, controllers: { sessions: "users/sessions", 
                                    confirmations: "users/confirmations",
                                    registrations: "users/registrations", 
                                    passwords: "users/passwords",
                                    unlocks: "users/unlocks"}

end

edumax/app/models/article.rb
class Article < ActiveRecord::Base
    validates :title, presence: true
    validates :body, presence: true
    validates :author, presence: true
    validates_length_of :title, :minimum => 2, :maximum => 250, :allow_blank => false
    acts_as_taggable
end

edumax/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.page(params[:page]).per(5).order("created_at DESC")  
    @users = User.all
    @recent = Article.all.order("created_at desc").limit(5)
  end

  def tag
    @articles = Article.tagged_with(params[:tag]).page(params[:page]).per(5).order("created_at DESC")
    @users = User.all
    @recent = Article.all.order("created_at desc").limit(5)
    render :action => 'index'

  end

  def show
    @users = User.all
    @recent = Article.all.order("created_at desc").limit(5)
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
    @users = User.all
    @recent = Article.all.order("created_at desc").limit(5)
  end

  def delete
    @done = Article.find(params[:id])
    if @done.destroy
      redirect_to articles_path, notice: "The article has been successfully deleted."
    else
      redirect_to articles_path, notice: "The article could not be deleted."
    end
  end

  def create
    @recent = Article.all.order("created_at desc").limit(5)
    @article = Article.new(article_params)
    @article.author = current_user.id
    if @article.save
      redirect_to articles_path, notice: "The article has been successfully created."
    else
      flash[:error] = @article.errors.full_messages
      render :new
    end
  end

  def edit
    @recent = Article.all.order("created_at desc").limit(5)
    @article = Article.find(params[:id])
  end

  def update
    @recent = Article.all.order("created_at desc").limit(5)
    @article = Article.find(params[:id])
    if @article.update_attributes(article_params)
      redirect_to articles_path, notice: "The article has been successfully updated."
    else
      render action: "edit"
    end
  end



private

  def article_params
    params.require(:article).permit(:title, :body, :author, :tag_list)
  end
end

edumax/app/helpers/articles_helper.rb
module ArticlesHelper
end

edumax/app/views/articles/edit.html.erb
<div class="col-md-9 col-md-offset-3">
    <div class='row'>

        <div class="col-md-10 col-md-offset-1">
            <h1 style='color:#22aaaa;'><%= "Editing #{@article.title}" %></h1>
            <%= render "layouts/error" %>
            <div class='article_post'>
                <div class='modal-body'>
                
                <%= render "layouts/article_form" %>
            </div>
            </div>
            <br>
        </div>
    </div>
</div>


<%= render 'layouts/sidepanel'%>

edumax/app/views/articles/index.html.erb
    <div class="col-md-9 col-md-offset-3">
        <div class='row'>
            <div class="col-md-10 col-md-offset-1">
                
                <h1 style='color:#22aaaa;'><span class="glyphicon glyphicon-th-large" aria-hidden="true"></span> Edumax Blog</h1>
                <%= render 'layouts/error' %>
            </br>
                <% @articles.each do |article| %>
                    <div class='article_post'>
                        <div class='modal-body wordwrap'>
                            <%= image_tag @users.find(article.author).image.url(:smallish), {class: " circular-smallish f_right"} %>
                            <h3><%= link_to article.title, {:controller => 'articles', :action =>'show', :id => article.id} %>  </h3>

                             <p class="text-muted"><small>Posted on: <%=article.created_at.strftime("%B #{current_user.created_at.day.ordinalize}, %Y")%>| by <%= @users.find(article.author).first_name%>
                                <%= @users.find(article.author).last_name%>
                            </small><p>
                           
                            <p><%= article.body.html_safe %></p>
                            <%= link_to "Edit", edit_article_path(article) %> |
                             <%= link_to "Delete", {:controller => '/articles', :action => "delete", :id => article.id} %>
                             <p>Tags: <%= raw article.tag_list.map { |t| link_to t, { :action => :tag, :tag => t }, {class: 'label label-info'}}.join(' ') %></p>

                        </div>
                    </div>
                    <% if article != @articles.last %>
                    <br />
                    <% end %>
                    
                <% end %>
                <div class="text-center"><%= paginate @articles, :theme => 'twitter-bootstrap-3' %></div>
            </div>
        </div>
    </div>  



<%= render 'layouts/sidepanel'%>

edumax/app/views/articles/new.html.erb
    <div class="col-md-9 col-md-offset-3">
        <div class='row'>

            <div class="col-md-10 col-md-offset-1">
        <%= render "layouts/error" %>
        <div class='article_post'>
    
            <h3> New Article</h3>
            <%= render "layouts/article_form" %>
        </div>
    </div>
                </div>
        </div>
    </div>  

<%= render 'layouts/sidepanel'%>

edumax/app/views/articles/show.html.erb
    <div class="col-md-9 col-md-offset-3">
        <div class='row'>
            <div class="col-md-10 col-md-offset-1">
                
                <h1 style='color:#22aaaa;'><span class="glyphicon glyphicon-th-large" aria-hidden="true"></span> Edumax Blog</h1>
                <%= render 'layouts/error' %>
            </br>
                    <div class='article_post'>
                        <div class='modal-body wordwrap'>
                            <%= image_tag @users.find(@article.author).image.url(:smallish), {class: " circular-smallish"} %>
                            <h3><%= @article.title.html_safe %>  </h3>

                             <p class="text-muted"><small>Posted on: <%=@article.created_at.strftime("%B #{current_user.created_at.day.ordinalize}, %Y")%>| by <%= @users.find(@article.author).first_name%>
                                <%= @users.find(@article.author).last_name%>
                            </small><p>
                           
                            <p><%= @article.body.html_safe %></p>
                            <%= link_to "Edit", edit_article_path(@article) %> |
                             <%= link_to "Delete", {:controller => 'articles', :action => "delete", :id => @article.id} %>
                             <p>Tags: <%= raw @article.tag_list.map { |t| link_to t, { :action => :tag, :tag => t }, {class: 'label label-info'}}.join(' ') %></p>

                        </div>
                    </div>
            </div>
        </div>
    </div>  



<%= render 'layouts/sidepanel'%>